#!/usr/bin/env python3
"""Prepare the immutable, reproducible Homebrew source asset and formula.

Only build inputs and their licences are packaged. No checkout, build cache,
personal configuration, credentials, or private evidence enters this asset.
"""
import gzip
import subprocess
import sys
import hashlib
import json
import pathlib
import re
import tarfile

root = pathlib.Path(__file__).resolve().parent.parent
version = re.search(r'current = "([0-9]+\.[0-9]+\.[0-9]+)"', (root / "Sources/RightClickCore/ProductSurface.swift").read_text())[1]
output = root / "dist" / f"rightclick-{version}-source.tar.gz"
# Durably record substrate kinds inside the immutable source asset so
# detect-bottle-alignment.py can inventory a published bottle without guessing.
manifest = root / "packaging" / "substrate-kinds.json"
subprocess.check_call(
    [sys.executable, str(root / "scripts" / "detect-bottle-alignment.py"),
     "--write-manifest", str(manifest)],
    cwd=str(root),
)

inputs = ["Package.swift", "Package.resolved", "LICENSE", "Sources", "Tests", "Vendor",
          "fixtures", "packaging/ThirdPartyLicenses", "packaging/substrate-kinds.json",
          "scripts/build-cli.sh"]
paths = []
for name in inputs:
    path = root / name
    assert path.exists(), name
    paths.append(path)
    if path.is_dir():
        paths.extend(path.rglob("*"))
# The shipped Tests target uses real subprocess fixtures and shared helpers.
# Keep their source closure, including future fixture additions, rather than
# packaging only one historical provider. Git's tracked inventory excludes
# generated bytecode, diagnostics and private local files from scripts/.
script_modes = {}
for entry in subprocess.check_output(
        ["git", "ls-files", "--stage", "-z", "--", "scripts"], cwd=root).decode("utf-8").split("\0"):
    if not entry:
        continue
    metadata, relative = entry.split("\t", 1)
    mode, _, stage = metadata.split()
    assert stage == "0", "Resolve script conflicts before packaging."
    path = root / relative
    assert path.is_file() and not path.is_symlink(), relative
    script_modes[relative] = int(mode, 8)
    paths.append(path)
output.parent.mkdir(parents=True, exist_ok=True)
with output.open("wb") as raw:
    with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as gz:
        with tarfile.open(fileobj=gz, mode="w", format=tarfile.USTAR_FORMAT) as archive:
            for path in sorted(set(paths)):
                assert not path.is_symlink(), path
                relative = path.relative_to(root)
                assert ".DS_Store" not in relative.parts, relative
                info = archive.gettarinfo(str(path), arcname=f"rightclick-{version}/{relative}")
                info.uid = info.gid = 0
                info.uname = info.gname = "root"
                info.mtime = 1767225600
                info.mode = 0o755 if (path.is_dir() or relative.as_posix() == "scripts/build-cli.sh"
                    or script_modes.get(relative.as_posix(), 0) & 0o111) else 0o644
                if info.isfile():
                    with path.open("rb") as stream:
                        archive.addfile(info, stream)
                else:
                    archive.addfile(info)
digest = hashlib.sha256(output.read_bytes()).hexdigest()
template = (root / "packaging/homebrew/rightclick.rb.in").read_text()
bottle = root / "packaging/homebrew/bottle.json"
block = ""
if bottle.exists():
    metadata = json.loads(bottle.read_text())
    # Legacy metadata belongs to the immutable 0.1.0 release. Never attach it
    # to a different version or relax its source hash check.
    if metadata.get("version", "0.1.0") == version:
        if metadata["source_sha256"] != digest:
            raise RuntimeError("The published bottle pins different source. Prepare a new version; do not replace the published artifact.")
        block = metadata["dsl"] + "\n"
formula = template.replace("@VERSION@", version).replace("@SOURCE_SHA256@", digest).replace("@BOTTLE_BLOCK@\n", block)
for name in ["packaging/homebrew/rightclick.rb", "packaging/tap/Formula/rightclick.rb"]:
    (root / name).write_text(formula)
(output.parent / "SHA256SUMS-source").write_text(f"{digest}  {output.name}\n")
print(f"{digest}  {output.name}")
